/branches/1.3.x:
Merged revision 6068 from trunk.

r6068 | sa | 2009-09-04 13:50:55 CEST

trunk:

SVNAdminArea16:
 - addTreeConflict(): improve 'tree conflict already exists'
   error: include the path of.svn catalog where 
   the conflict is created to the error message.